### PR TITLE
replace msgpack library

### PR DESCRIPTION
**Pull request by nicolasparada**
Replace msgpack library from `github.com/ugorji/go/codec` to `github.com/vmihailenco/msgpack/v5`.

There are still references to the old library in the subppackages that I didn't want to touch yet.

It has better support for (un)marshalling types like `time.Time` making tests more expectables.

Also included tests from #https://github.com/chronosphereio/calyptia-plugin/pull/68 and msgpack unmarshalling into `map[string]any` instead of `map[string]string`.

Also did some chores and updated some dependencies, addressed some lint issues, etc.

### CODE REVIEW

**Comment by nicolasparada** [comment]
Notice that CI is failing, but it was failing from before. There are too many lint problems (maybe the linter is too strict considering we are using many C idioms).

**Review by cosmo0920 — COMMENTED** [review]
I confirmed that this change should not affect hot-reloading. And working as intended. But I'm still processing for how this replacement works.

**Review by cosmo0920 — APPROVED** [review]
All confirmed for time related things. Looks attractive. :+1:

**Comment by nicolasparada** [comment]
Right. This does not fixes the issue that fluent-bit still renders Go's `time.Time` type as bytes.

**Review by jasmingacic — APPROVED** [review]
If I'm reading this correctly this is mostly refactoring to replace the library. 
If that's the case it looks good to me

**Pull request merged**
